name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps --ignore-scripts
          npm install --save-dev @babel/plugin-proposal-private-property-in-object@7.21.11

      - name: Build
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          CI=false npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          folder: ./build