name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: ""  # Clear NODE_OPTIONS at job level
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Install Dependencies
        run: |
          npm install --ignore-scripts --no-audit --no-fund --omit=optional
          find . -name "ejs" -type d -exec rm -rf {} +
          npm install --no-package-lock --ignore-scripts

      - name: Build
        run: |
          unset NODE_OPTIONS
          CI=false DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          folder: ./build