name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          # Install without running any scripts
          npm install --ignore-scripts
          
          # Install core-js separately without postinstall
          npm install core-js@2.6.12 --ignore-scripts
          
          # Install babel-runtime without scripts
          npm install babel-runtime --ignore-scripts

      - name: Build
        run: npm run build
        env:
          CI: false
          SKIP_PREFLIGHT_CHECK: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          folder: ./build