name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps --no-audit
        env:
          NODE_OPTIONS: ""

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          folder: ./build
