name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      npm_config_ignore_scripts: true
      NODE_OPTIONS: ""
      OPENSSL_CONF: /dev/null
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Install Dependencies
        env:
          NODE_OPTIONS: ""
        run: |
          npm install --legacy-peer-deps --no-optional --ignore-scripts
          npm install --save-dev @babel/plugin-transform-private-property-in-object@7.21.11 --ignore-scripts

      - name: Build
        env:
          NODE_OPTIONS: ""
          CI: false
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          folder: ./build